// Add these imports at the top of your App.jsx / App.tsx
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

// Add this function inside your App component (or in a separate utils file)
const downloadMessageAsPDF = async (messageContent, messageIndex) => {
    try {
        // Create a temporary hidden container to render the markdown content properly
        const container = document.createElement('div');
        container.style.position = 'absolute';
        container.style.left = '-9999px';
        container.style.top = '-9999px';
        container.style.width = '595px'; // A4 width in pt (210mm)
        container.style.padding = '40px';
        container.style.backgroundColor = '#ffffff';
        container.style.color = '#000000';
        container.style.fontFamily = 'Helvetica, Arial, sans-serif';
        container.style.fontSize = '11pt';
        container.style.lineHeight = '1.5';
        container.style.boxSizing = 'border-box';

        // Basic markdown styling (you can enhance this further)
        const style = document.createElement('style');
        style.textContent = `
      h1, h2, h3, h4 { color: #1a1a1a; margin: 1.2em 0 0.6em; }
      h1 { font-size: 18pt; }
      h2 { font-size: 15pt; }
      h3 { font-size: 13pt; }
      p, ul, ol { margin: 0.8em 0; }
      strong { font-weight: bold; }
      em { font-style: italic; }
      code { font-family: 'Courier New', monospace; background: #f5f5f5; padding: 2px 4px; border-radius: 3px; }
      pre { background: #f8f8f8; padding: 12px; border-radius: 6px; overflow-x: auto; margin: 1em 0; }
      ul, ol { padding-left: 24px; }
      li { margin-bottom: 0.5em; }
      table { border-collapse: collapse; width: 100%; margin: 1em 0; }
      th, td { border: 1px solid #ddd; padding: 8px; }
      th { background: #f2f2f2; }
      blockquote { border-left: 4px solid #ccc; padding-left: 12px; color: #555; margin: 1em 0; }
      hr { border: none; border-top: 1px solid #eee; margin: 1.5em 0; }
    `;
        container.appendChild(style);

        // Header
        const header = document.createElement('div');
        header.innerHTML = `
      <h1 style="font-size: 20pt; margin-bottom: 24px; color: #4f46e5;">MindKore AI Message #${messageIndex + 1}</h1>
      <p style="color: #666; font-size: 10pt; margin-bottom: 24px;">
        Generated on ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}
      </p>
    `;
        container.appendChild(header);

        // Markdown content
        const contentDiv = document.createElement('div');
        contentDiv.innerHTML = messageContent
            .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')           // bold
            .replace(/\*(.*?)\*/g, '<em>$1</em>')                      // italic
            .replace(/```([\s\S]*?)```/g, '<pre><code>$1</code></pre>') // code blocks
            .replace(/`([^`]+)`/g, '<code>$1</code>')                  // inline code
            .replace(/^### (.*$)/gm, '<h3>$1</h3>')                    // h3
            .replace(/^## (.*$)/gm, '<h2>$1</h2>')                     // h2
            .replace(/^# (.*$)/gm, '<h1>$1</h1>')                      // h1
            .replace(/^- (.*$)/gm, '<li>$1</li>')                      // simple list (ul)
            .replace(/\n/g, '<br>');                                   // line breaks

        // Wrap lists properly
        contentDiv.innerHTML = contentDiv.innerHTML.replace(/(<li>.*?<\/li>)/gs, '<ul>$1</ul>');

        container.appendChild(contentDiv);

        // Footer
        const footer = document.createElement('div');
        footer.innerHTML = `
      <hr style="margin: 40px 0 20px;">
      <p style="text-align: center; color: #888; font-size: 9pt;">
        Generated by MindKore AI • Confidential • ${new Date().getFullYear()}
      </p>
    `;
        container.appendChild(footer);

        document.body.appendChild(container);

        // Wait for rendering
        await new Promise(resolve => setTimeout(resolve, 300));

        // Generate canvas
        const canvas = await html2canvas(container, {
            scale: 2,
            useCORS: true,
            logging: false,
            backgroundColor: '#ffffff',
            windowWidth: 595,
            windowHeight: container.scrollHeight,
        });

        const imgData = canvas.toDataURL('image/png');

        // Create PDF
        const pdf = new jsPDF({
            orientation: 'portrait',
            unit: 'pt',
            format: 'a4',
        });

        const pageWidth = pdf.internal.pageSize.getWidth();
        const pageHeight = pdf.internal.pageSize.getHeight();
        const imgWidth = canvas.width / 2; // scale=2
        const imgHeight = canvas.height / 2;

        let heightLeft = imgHeight;
        let position = 0;

        // First page
        pdf.addImage(imgData, 'PNG', 0, position, pageWidth, imgHeight);
        heightLeft -= pageHeight;

        // Additional pages if content is long
        while (heightLeft >= 0) {
            position = heightLeft - imgHeight;
            pdf.addPage();
            pdf.addImage(imgData, 'PNG', 0, position, pageWidth, imgHeight);
            heightLeft -= pageHeight;
        }

        pdf.save(`mindkore-ai-message-${messageIndex + 1}.pdf`);

        // Cleanup
        document.body.removeChild(container);
    } catch (error) {
        console.error('PDF generation failed:', error);
        alert('Failed to generate PDF. Please try again.');
    }
};


export default downloadMessageAsPDF; 